name: Build APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install dependencies
      run: npm install

    - name: Setup Expo CLI
      run: npm install -g @expo/cli eas-cli

    - name: Expo Login
      run: npx expo login -u ${{ secrets.EXPO_USERNAME }} -p ${{ secrets.EXPO_PASSWORD }}
      env:
        EXPO_USERNAME: ${{ secrets.EXPO_USERNAME }}
        EXPO_PASSWORD: ${{ secrets.EXPO_PASSWORD }}

    - name: Build APK with EAS
      run: |
        npx eas build --platform android --profile preview --local --output signademy.apk
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: signademy-apk
        path: 'signademy.apk'
        retention-days: 30

    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.0.${{ github.run_number }}
        name: Signademy v1.0.${{ github.run_number }}
        body: |
          🤟 **Signademy APK Build**
          
          **Changes in this build:**
          - Frame-by-frame sign language detection
          - Google MediaPipe integration
          - Camera controls (enable/disable, flip)
          - Simple splash screen
          
          **Installation:**
          1. Download the APK file below
          2. Enable "Install from unknown sources" on your Android device
          3. Install the APK
          4. Grant camera permissions when prompted
          
          **Note:** This is a development build for testing purposes.
        files: 'signademy.apk'
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
